# Generated by Django 3.0.5 on 2020-06-09 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0007_delete_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.DateTimeField(default=django.utils.timezone.now)),
                ('etime', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('cart', models.ManyToManyField(to='home.Carts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('street', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('houseno', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('dist', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
