# Generated by Django 3.0.5 on 2020-06-09 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='etime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
